# Generated by Django 5.2.15 on 2026-06-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_coursegroup_level_alter_student_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Niveau', 'verbose_name_plural': 'Niveaux'},
        ),
        migrations.RemoveField(
            model_name='level',
            name='order',
        ),
        migrations.AddField(
            model_name='level',
            name='category',
            field=models.CharField(choices=[('PRIMAIRE', 'Primaire'), ('COLLEGE', 'Collège'), ('LYCEE', 'Lycée')], default='PRIMAIRE', max_length=20, verbose_name='Catégorie'),
        ),
    ]
