# Generated by Django 5.2.15 on 2026-06-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_level_options_remove_level_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='whatsapp_group_link',
            field=models.URLField(blank=True, null=True, verbose_name='Lien du groupe WhatsApp'),
        ),
    ]
