# Generated by Django 5.2.15 on 2026-06-23 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_coursegroup_whatsapp_group_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('message_type', models.CharField(choices=[('payment_reminder', 'Rappel de paiement'), ('payment_confirmation', 'Confirmation de paiement'), ('absence_notification', "Notification d'absence"), ('session_reminder', 'Rappel de séance'), ('bulk_announcement', 'Annonce groupée'), ('other', 'Autre')], default='other', max_length=30, verbose_name='Type de message')),
                ('message_preview', models.TextField(blank=True, max_length=300, verbose_name='Aperçu du message')),
                ('status', models.CharField(choices=[('SENT', 'Envoyé'), ('FAILED', 'Échec')], default='SENT', max_length=10, verbose_name='Statut')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to='core.student', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Journal WhatsApp',
                'verbose_name_plural': 'Journal WhatsApp',
                'ordering': ['-sent_at'],
            },
        ),
    ]
