# Generated by Django 5.2.15 on 2026-06-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_whatsappsendlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionException',
        ),
    ]
