# Generated by Django 5.2.15 on 2026-06-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_delete_sessionexception'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du congé / jour férié')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('affects_all', models.BooleanField(default=True, help_text="Si coché, aucun groupe n'a de séance ce jour-là.", verbose_name='Tous les groupes')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affected_groups', models.ManyToManyField(blank=True, help_text='Laissez vide si tous les groupes sont concernés (option ci-dessus cochée).', related_name='holidays', to='core.coursegroup', verbose_name='Groupes concernés')),
            ],
            options={
                'verbose_name': 'Jour férié / Congé',
                'verbose_name_plural': 'Jours fériés / Congés',
                'ordering': ['date'],
            },
        ),
    ]
