# Generated by Django 5.2.15 on 2026-06-23 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_holiday_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Lundi'), ('TUE', 'Mardi'), ('WED', 'Mercredi'), ('THU', 'Jeudi'), ('FRI', 'Vendredi'), ('SAT', 'Samedi'), ('SUN', 'Dimanche')], max_length=3, verbose_name='Jour')),
                ('start_time', models.TimeField(verbose_name='Début disponibilité')),
                ('end_time', models.TimeField(verbose_name='Fin disponibilité')),
                ('is_available', models.BooleanField(default=True, help_text='Décocher pour marquer un créneau comme indisponible.', verbose_name='Disponible')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='core.teacher', verbose_name='Professeur')),
            ],
            options={
                'verbose_name': 'Disponibilité professeur',
                'verbose_name_plural': 'Disponibilités professeurs',
                'ordering': ['teacher', 'day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TeacherLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('SICK', 'Maladie'), ('VACATION', 'Congé annuel'), ('PERSONAL', 'Raison personnelle'), ('OTHER', 'Autre')], default='OTHER', max_length=10, verbose_name='Type de congé')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='core.teacher', verbose_name='Professeur')),
            ],
            options={
                'verbose_name': 'Congé professeur',
                'verbose_name_plural': 'Congés professeurs',
                'ordering': ['-start_date'],
            },
        ),
    ]
