# Generated by Django 5.2.15 on 2026-06-23 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_teacher_leave_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_makeup',
            field=models.BooleanField(default=False, verbose_name='Séance de rattrapage'),
        ),
        migrations.AddField(
            model_name='session',
            name='makeup_for',
            field=models.OneToOneField(blank=True, help_text='Séance annulée que ce rattrapage remplace.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='makeup_session', to='core.session', verbose_name='Rattrapage de la séance'),
        ),
    ]
