# Generated by Django 5.2.15 on 2026-06-23 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_add_session_makeup_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('CANCELLED', 'Séance annulée'), ('RESCHEDULED', 'Séance reprogrammée'), ('ROOM_CHANGED', 'Changement de salle'), ('SUBSTITUTE', 'Professeur remplaçant'), ('MAKEUP', 'Séance de rattrapage planifiée')], max_length=15)),
                ('message', models.TextField(verbose_name='Message de notification')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyé'), ('FAILED', 'Échoué'), ('SKIPPED', 'Ignoré')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.session')),
            ],
            options={
                'verbose_name': 'Notification de changement',
                'verbose_name_plural': 'Notifications de changements',
                'ordering': ['-created_at'],
            },
        ),
    ]
