# Generated by Django 5.2.15 on 2026-06-23 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_schedule_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulenotification',
            name='session',
        ),
        migrations.RemoveField(
            model_name='teacheravailability',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teacherleave',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='session',
            name='is_makeup',
        ),
        migrations.RemoveField(
            model_name='session',
            name='makeup_for',
        ),
        migrations.DeleteModel(
            name='Holiday',
        ),
        migrations.DeleteModel(
            name='ScheduleNotification',
        ),
        migrations.DeleteModel(
            name='TeacherAvailability',
        ),
        migrations.DeleteModel(
            name='TeacherLeave',
        ),
    ]
