# Generated by Django 5.2.15 on 2026-06-27 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_schedulenotification_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du congé / jour férié')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('affects_all', models.BooleanField(default=True, help_text="Si coché, aucun groupe n'a de séance ce jour-là.", verbose_name='Tous les groupes')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Jour férié / Congé',
                'verbose_name_plural': 'Jours fériés / Congés',
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='core.session', verbose_name='Séance'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='core_attend_date_801bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['course_group', 'date'], name='core_attend_course__56f393_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['status'], name='core_sessio_status_45f1a3_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['date', 'status'], name='core_sessio_date_5a0a96_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['group', 'date'], name='core_sessio_group_i_55c64f_idx'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='affected_groups',
            field=models.ManyToManyField(blank=True, help_text='Laissez vide si tous les groupes sont concernés (option ci-dessus cochée).', related_name='holidays', to='core.coursegroup', verbose_name='Groupes concernés'),
        ),
    ]
