# Generated by Django 5.2.15 on 2026-06-27 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_phase1_optimizations'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeupSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('makeup_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makeups', to='core.session', verbose_name='Séance de rattrapage')),
                ('original_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='makeup_origins', to='core.session', verbose_name="Séance d'origine")),
                ('students', models.ManyToManyField(blank=True, related_name='makeup_sessions', to='core.student', verbose_name='Élèves concernés')),
            ],
            options={
                'verbose_name': 'Séance de rattrapage',
                'verbose_name_plural': 'Séances de rattrapage',
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Lundi'), ('TUE', 'Mardi'), ('WED', 'Mercredi'), ('THU', 'Jeudi'), ('FRI', 'Vendredi'), ('SAT', 'Samedi'), ('SUN', 'Dimanche')], max_length=3, verbose_name='Jour')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='core.teacher', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Disponibilité enseignant',
                'verbose_name_plural': 'Disponibilités enseignants',
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TeacherLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('leave_type', models.CharField(choices=[('SICK', 'Maladie'), ('VACATION', 'Vacances'), ('OTHER', 'Autre')], default='OTHER', max_length=10, verbose_name='Type de congé')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='core.teacher', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Congé enseignant',
                'verbose_name_plural': 'Congés enseignants',
                'ordering': ['-start_date'],
            },
        ),
    ]
