# Generated by Django 5.2.15 on 2026-07-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_teacher_leave_availability_makeupsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='main_school',
            field=models.CharField(blank=True, max_length=150, verbose_name='Établissement principal'),
        ),
        migrations.AlterField(
            model_name='level',
            name='category',
            field=models.CharField(choices=[('GARDERIE', 'La Garderie'), ('PRIMAIRE', 'Primaire'), ('COLLEGE', 'Collège'), ('LYCEE', 'Lycée')], default='PRIMAIRE', max_length=20, verbose_name='Catégorie'),
        ),
    ]
