# Generated by Django 5.2.15 on 2026-07-07 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_student_main_school_alter_level_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="LevelCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom de la catégorie"
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=50, unique=True, verbose_name="Code"),
                ),
            ],
            options={
                "verbose_name": "Catégorie de niveau",
                "verbose_name_plural": "Catégories de niveau",
                "ordering": ["name"],
            },
        ),
        migrations.RenameField(
            model_name="level",
            old_name="category",
            new_name="category_old",
        ),
        migrations.AddField(
            model_name="level",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="levels",
                to="core.levelcategory",
                verbose_name="Catégorie",
            ),
        ),
    ]
