# Generated by Django 5.2.15 on 2026-07-07 12:27

from django.db import migrations


def populate_categories(apps, schema_editor):
    LevelCategory = apps.get_model('core', 'LevelCategory')
    Level = apps.get_model('core', 'Level')

    # Categories default data
    default_categories = [
        ('GARDERIE', 'La Garderie'),
        ('PRIMAIRE', 'Primaire'),
        ('COLLEGE', 'Collège'),
        ('LYCEE', 'Lycée'),
    ]

    category_map = {}
    for code, name in default_categories:
        cat, created = LevelCategory.objects.get_or_create(code=code, defaults={'name': name})
        category_map[code] = cat

    # Map existing Level category_old to category ForeignKey
    for level in Level.objects.all():
        old_cat = level.category_old
        if old_cat in category_map:
            level.category = category_map[old_cat]
            level.save()


def reverse_categories(apps, schema_editor):
    Level = apps.get_model('core', 'Level')
    LevelCategory = apps.get_model('core', 'LevelCategory')

    for level in Level.objects.all():
        if level.category:
            level.category_old = level.category.code
            level.save()

    LevelCategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_levelcategory_level_category_old_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_categories, reverse_code=reverse_categories),
    ]
