# Generated by Django 5.2.15 on 2026-07-07 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_migrate_level_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="level",
            name="category_old",
        ),
        migrations.AlterField(
            model_name="level",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="levels",
                to="core.levelcategory",
                verbose_name="Catégorie",
            ),
        ),
    ]
