# Generated by Django 5.2.15 on 2026-07-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_remove_level_category_old_alter_level_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="matricule",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Matricule",
            ),
        ),
    ]
