# Generated by Django 5.2.15 on 2026-07-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_student_matricule"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("student", "course_group", "date"),
                name="unique_attendance_per_student_group_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                fields=("student", "course_group"),
                name="unique_enrollment_per_student_course_group",
            ),
        ),
    ]
