# Generated by Django 5.2.15 on 2026-07-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_alter_attendance_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("content", models.TextField(verbose_name="Contenu")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "Annonce générale"),
                            ("event", "Événement à venir"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "event_date",
                    models.DateField(
                        blank=True,
                        help_text="Requis pour les événements à venir",
                        null=True,
                        verbose_name="Date de l'événement",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Laissez vide pour afficher à tous les groupes",
                        related_name="announcements",
                        to="core.coursegroup",
                        verbose_name="Groupes cibles",
                    ),
                ),
                (
                    "target_levels",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Laissez vide pour afficher à tous les niveaux",
                        related_name="announcements",
                        to="core.level",
                        verbose_name="Niveaux cibles",
                    ),
                ),
            ],
            options={
                "verbose_name": "Annonce / Événement",
                "verbose_name_plural": "Annonces & Événements",
                "ordering": ["-created_at"],
            },
        ),
    ]
