# Generated by Django 5.2.15 on 2026-07-12 18:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_announcement"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Montant (DH)",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de paiement",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Espèces"),
                            ("TRANSFER", "Virement"),
                            ("CHECK", "Chèque"),
                        ],
                        default="CASH",
                        max_length=20,
                        verbose_name="Mode de paiement",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("ADVANCE", "Avance / Acompte"),
                            ("SALARY", "Règlement de salaire"),
                            ("ADJUSTMENT", "Régularisation"),
                        ],
                        default="SALARY",
                        max_length=20,
                        verbose_name="Type de paiement",
                    ),
                ),
                (
                    "period_month",
                    models.PositiveSmallIntegerField(verbose_name="Mois de la période"),
                ),
                (
                    "period_year",
                    models.PositiveSmallIntegerField(
                        verbose_name="Année de la période"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes / Détails")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_payments",
                        to="core.teacher",
                        verbose_name="Enseignant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement Enseignant",
                "verbose_name_plural": "Paiements Enseignants",
                "ordering": ["-payment_date", "-id"],
            },
        ),
    ]
