# Generated by Django 5.2.15 on 2026-07-12 20:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_teacherpayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Réduction (DH)",
            ),
        ),
    ]
