# Generated by Django 5.2.15 on 2026-07-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_payment_discount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="discount",
        ),
    ]
