# Generated by Django 5.2.15 on 2026-07-16 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_remove_payment_discount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(default=True, verbose_name="Verrouillé"),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de début"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                (
                    "academic_year",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Année académique",
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Verrouillé le"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verrouillé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verrouillage du planning",
                "verbose_name_plural": "Verrouillages du planning",
            },
        ),
        migrations.CreateModel(
            name="SessionChangeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date/Heure"),
                ),
                (
                    "previous_values",
                    models.JSONField(default=dict, verbose_name="Valeurs précédentes"),
                ),
                (
                    "new_values",
                    models.JSONField(default=dict, verbose_name="Nouvelles valeurs"),
                ),
                (
                    "change_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Motif du changement"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                ("action", models.CharField(max_length=50, verbose_name="Action")),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_history",
                        to="core.session",
                        verbose_name="Séance",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de modification de séance",
                "verbose_name_plural": "Historiques de modifications de séances",
                "ordering": ["-timestamp"],
            },
        ),
    ]
