# Generated by Django 5.2.15 on 2026-07-16 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_schedulelock_sessionchangehistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="parent_contact",
        ),
        migrations.RemoveField(
            model_name="student",
            name="parent_name",
        ),
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nom complet")),
                (
                    "phone",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Téléphone"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tuteur / Parent",
                "verbose_name_plural": "Tuteurs / Parents",
                "indexes": [
                    models.Index(fields=["phone"], name="core_guardi_phone_5b8dee_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentGuardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Lien de parenté"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=True, verbose_name="Tuteur principal"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_guardians",
                        to="core.guardian",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_guardians",
                        to="core.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relation Élève-Tuteur",
                "verbose_name_plural": "Relations Élèves-Tuteurs",
                "unique_together": {("student", "guardian")},
            },
        ),
        migrations.AddField(
            model_name="student",
            name="guardians",
            field=models.ManyToManyField(
                related_name="students",
                through="core.StudentGuardian",
                to="core.guardian",
                verbose_name="Tuteurs",
            ),
        ),
    ]
