# Generated by Django 5.2.15 on 2026-07-16 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_add_student_parent_contact_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionchangehistory",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="change_history",
                to="core.session",
                verbose_name="Séance",
            ),
        ),
    ]
