# Generated by Django 5.2.15 on 2026-07-16 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_add_session_change_history_nullability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coursegroup",
            name="requires_accessibility",
            field=models.BooleanField(
                default=False, verbose_name="Requiert accessibilité"
            ),
        ),
        migrations.AddField(
            model_name="coursegroup",
            name="requires_air_conditioning",
            field=models.BooleanField(
                default=False, verbose_name="Requiert climatisation"
            ),
        ),
        migrations.AddField(
            model_name="coursegroup",
            name="requires_computer_lab",
            field=models.BooleanField(default=False, verbose_name="Requiert labo info"),
        ),
        migrations.AddField(
            model_name="coursegroup",
            name="requires_projector",
            field=models.BooleanField(
                default=False, verbose_name="Requiert projecteur"
            ),
        ),
        migrations.AddField(
            model_name="coursegroup",
            name="requires_science_lab",
            field=models.BooleanField(
                default=False, verbose_name="Requiert labo science"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="accessibility",
            field=models.BooleanField(default=False, verbose_name="Accessible PMR"),
        ),
        migrations.AddField(
            model_name="room",
            name="building",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Bâtiment"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="floor",
            field=models.IntegerField(blank=True, null=True, verbose_name="Étage"),
        ),
        migrations.AddField(
            model_name="room",
            name="has_air_conditioning",
            field=models.BooleanField(default=False, verbose_name="Climatisation"),
        ),
        migrations.AddField(
            model_name="room",
            name="has_computer_lab",
            field=models.BooleanField(
                default=False, verbose_name="Laboratoire informatique"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="has_projector",
            field=models.BooleanField(default=False, verbose_name="Projecteur"),
        ),
        migrations.AddField(
            model_name="room",
            name="has_science_lab",
            field=models.BooleanField(
                default=False, verbose_name="Laboratoire scientifique"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="schedule_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Brouillon"),
                    ("PUBLISHED", "Publié"),
                    ("ARCHIVED", "Archivé"),
                ],
                default="PUBLISHED",
                max_length=15,
                verbose_name="État de planification",
            ),
        ),
        migrations.CreateModel(
            name="AcademicCalendarPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nom de la période"),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("HOLIDAY", "Holiday"),
                            ("VACATION", "Vacation"),
                            ("EXAM_WEEK", "Exam Week"),
                            ("CLOSURE", "Institution Closure"),
                        ],
                        default="VACATION",
                        max_length=20,
                        verbose_name="Type de période",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Date de début")),
                ("end_date", models.DateField(verbose_name="Date de fin")),
                (
                    "affects_all",
                    models.BooleanField(
                        default=True,
                        help_text="Si coché, affecte tous les groupes durant cette période.",
                        verbose_name="Affecte tous les groupes",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "affected_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="academic_periods",
                        to="core.coursegroup",
                        verbose_name="Groupes concernés",
                    ),
                ),
            ],
            options={
                "verbose_name": "Période du Calendrier Académique",
                "verbose_name_plural": "Périodes du Calendrier Académique",
                "ordering": ["start_date"],
            },
        ),
        migrations.CreateModel(
            name="RecurringException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("TEACHER", "Teacher"), ("ROOM", "Room")],
                        max_length=10,
                        verbose_name="Cible",
                    ),
                ),
                (
                    "recurrence_type",
                    models.CharField(
                        choices=[
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY_DAY", "Monthly Day (e.g. First Monday)"),
                        ],
                        max_length=20,
                        verbose_name="Type de récurrence",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MON", "Lundi"),
                            ("TUE", "Mardi"),
                            ("WED", "Mercredi"),
                            ("THU", "Jeudi"),
                            ("FRI", "Vendredi"),
                            ("SAT", "Samedi"),
                            ("SUN", "Dimanche"),
                        ],
                        max_length=3,
                        null=True,
                        verbose_name="Jour de la semaine",
                    ),
                ),
                (
                    "week_number",
                    models.IntegerField(
                        blank=True,
                        help_text="1 pour 1ère, 2 pour 2ème, -1 pour dernière, etc.",
                        null=True,
                        verbose_name="Numéro de semaine dans le mois",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Heure de début")),
                ("end_time", models.TimeField(verbose_name="Heure de fin")),
                (
                    "is_available",
                    models.BooleanField(
                        default=False,
                        help_text="Si décoché, signifie indisponibilité.",
                        verbose_name="Disponible",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=250, verbose_name="Notes"),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_exceptions",
                        to="core.room",
                        verbose_name="Salle",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_exceptions",
                        to="core.teacher",
                        verbose_name="Enseignant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exception récurrente",
                "verbose_name_plural": "Exceptions récurrentes",
            },
        ),
        migrations.CreateModel(
            name="RoomAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("MON", "Lundi"),
                            ("TUE", "Mardi"),
                            ("WED", "Mercredi"),
                            ("THU", "Jeudi"),
                            ("FRI", "Vendredi"),
                            ("SAT", "Samedi"),
                            ("SUN", "Dimanche"),
                        ],
                        max_length=3,
                        verbose_name="Jour",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Heure de début")),
                ("end_time", models.TimeField(verbose_name="Heure de fin")),
                (
                    "is_available",
                    models.BooleanField(default=False, verbose_name="Disponible"),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=200, verbose_name="Notes"),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="core.room",
                        verbose_name="Salle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disponibilité salle",
                "verbose_name_plural": "Disponibilités salles",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SCHEDULER", "Scheduler"),
                            ("TEACHER", "Teacher"),
                            ("ACADEMIC_MANAGER", "Academic Manager"),
                            ("BRANCH_MANAGER", "Branch Manager"),
                            ("AUDITOR", "Auditor"),
                            ("STUDENT", "Student"),
                        ],
                        default="STUDENT",
                        max_length=20,
                        verbose_name="Rôle",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_profile",
                        to="core.student",
                        verbose_name="Élève associé",
                    ),
                ),
                (
                    "teacher",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_profile",
                        to="core.teacher",
                        verbose_name="Enseignant associé",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
