# Generated by Django 5.2.15 on 2026-09-30 17:06

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_level_options_level_level_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Marqué comme soldé pour ce mois même si le montant perçu est inférieur au montant requis', verbose_name='Soldé par exception'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Libellé / Titre')),
                ('category', models.CharField(choices=[('RENT', 'Loyer & Charges'), ('UTILITIES', 'Eau, Électricité & Internet'), ('SALARY', 'Salaires & Primes du personnel'), ('SUPPLIES', 'Fournitures & Matériel pédagogique'), ('MAINTENANCE', 'Entretien & Réparations'), ('MARKETING', 'Marketing & Publicité'), ('TEACHER_PAY', 'Frais & Avances professeurs'), ('REFUND', 'Remboursement'), ('OTHER', 'Autre dépense')], default='OTHER', max_length=30, verbose_name='Catégorie')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant (DH)')),
                ('expense_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de dépense')),
                ('payment_method', models.CharField(choices=[('CASH', 'Espèces'), ('TRANSFER', 'Virement'), ('CHECK', 'Chèque')], default='CASH', max_length=10, verbose_name='Mode de règlement')),
                ('beneficiary', models.CharField(blank=True, max_length=200, verbose_name='Bénéficiaire / Fournisseur')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='N° Facture / Réf')),
                ('notes', models.TextField(blank=True, verbose_name='Remarques / Justificatif')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='Enregistré par')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['expense_date'], name='core_expens_expense_9af794_idx'), models.Index(fields=['category'], name='core_expens_categor_358de0_idx'), models.Index(fields=['payment_method'], name='core_expens_payment_85a64c_idx')],
            },
        ),
    ]
