# -*- coding: utf-8 -*-
"""
obfuscate_project.py
====================
Builds a fully-protected copy of this Django project into the ``dist/`` folder.

Protection layers
-----------------
  Python   -> Pyarmor 9 obfuscation for every .py file.
               Files that exceed SPLIT_THRESHOLD are split at top-level
               class/function boundaries into _part1.py, _part2.py, ...;
               the original filename becomes a thin re-export shim.
               Module-level preamble (loggers, constants, decorators, etc.)
               is placed in part 1 and referenced via an explicit import in
               all subsequent parts, so Python/Django semantics are
               preserved exactly.

  JS       -> javascript-obfuscator via npx (whatsapp_service/server.js)

  Templates-> Fernet symmetric encryption (AES-128-CBC + HMAC-SHA256).
               A fresh key is generated on every build and written into
               the dist copy of core/loaders.py before Pyarmor obfuscates
               it.  The key is embedded inside obfuscated bytecode, which
               significantly increases the reverse-engineering effort needed
               to extract it, but this is NOT equivalent to hardware-backed
               key storage (e.g. an HSM or TPM).  A sufficiently determined
               attacker with process-memory access or Pyarmor deobfuscation
               capability may still recover the key.

  Static   -> copied as-is (intentionally unprotected)

Usage
-----
  cd <project-root>
  python obfuscate_project.py           # normal build
  python obfuscate_project.py --clean   # delete dist/ only

Re-running is always safe; a new dist/ is built from scratch each time.
The build is atomic: work happens inside ``dist_tmp/`` which is renamed to
``dist/`` only on success.  A failed build leaves ``dist/`` untouched.
"""

import argparse
import ast
import os
import shutil
import subprocess
import sys
import tempfile
from typing import Optional

# ======================================================================
#  Named constants
# ======================================================================

# Output directory name (relative to project root)
DIST_DIR_NAME  = 'dist'
# Temporary build dir – moved to DIST_DIR_NAME only on success
DIST_TMP_NAME  = 'dist_tmp'
# Staging dir where files are split before obfuscation
STAGE_DIR_NAME = '_obf_stage'

# Pyarmor trial refuses scripts whose *source* exceeds ~32 KB.
# We split anything above this threshold before invoking Pyarmor.
# Set conservatively below the known working upper-bound.
SPLIT_THRESHOLD = 28 * 1024  # bytes

# Marker prefix prepended to every encrypted template
ENC_MARKER = b'FENC\x00'

# Python packages and top-level scripts to obfuscate
PYTHON_PACKAGES = ('core', 'school_erp')
PYTHON_SCRIPTS  = ('manage.py', 'run_server.py', 'fingerprint_generator.py')

# Sub-directories to skip for obfuscation (migrations are plain-copied)
OBFUSCATE_SKIP_DIRS = frozenset({'__pycache__', 'migrations', '.git'})

# A valid Pyarmor-obfuscated file must be at least this many bytes.
# Zero-byte or trivially small output indicates a failure.
MIN_OBFUSCATED_SIZE = 128  # bytes


# ======================================================================
#  Console helpers
# ======================================================================

def _banner(title: str) -> None:
    print(f"\n{'=' * 66}")
    print(f"  {title}")
    print('=' * 66)

def _info(msg: str)  -> None: print(f"    {msg}")
def _ok(msg: str)    -> None: print(f"  [OK]   {msg}")
def _warn(msg: str)  -> None: print(f"  [WARN] {msg}", file=sys.stderr)
def _fail(msg: str)  -> None: print(f"  [FAIL] {msg}", file=sys.stderr)


# ======================================================================
#  Fernet key generation and template encryption
# ======================================================================

def generate_fernet_key() -> bytes:
    """Return a new URL-safe base-64 encoded 32-byte Fernet key."""
    from cryptography.fernet import Fernet
    return Fernet.generate_key()


def fernet_encrypt(data: bytes, key: bytes) -> bytes:
    """Encrypt *data* with Fernet and prepend ENC_MARKER."""
    from cryptography.fernet import Fernet
    return ENC_MARKER + Fernet(key).encrypt(data)


# ======================================================================
#  loaders.py generator
#
#  core/loaders.py in the dist copy is regenerated to embed the Fernet
#  key before Pyarmor obfuscates it.  The key is NOT present in the
#  original source tree and never appears in plain text inside dist/.
# ======================================================================

LOADER_TEMPLATE = '''\
# Auto-generated by obfuscate_project.py.  Do NOT commit to VCS.
# The Fernet key below is embedded inside Pyarmor-obfuscated bytecode.
# Extracting it requires significant reverse-engineering effort, but it
# is not equivalent to hardware-backed secret storage.
from django.template.loaders.filesystem import Loader as FilesystemLoader
from django.template import TemplateDoesNotExist
from cryptography.fernet import Fernet as _Fernet

_FERNET_KEY = {key_repr}
_ENC_MARKER = {marker_repr}
_fernet     = _Fernet(_FERNET_KEY)


class DecryptedFilesystemLoader(FilesystemLoader):
    """Template loader that transparently decrypts Fernet-encrypted templates."""

    def get_contents(self, origin):
        try:
            with open(origin.name, 'rb') as fp:
                data = fp.read()
            if data.startswith(_ENC_MARKER):
                decrypted = _fernet.decrypt(data[len(_ENC_MARKER):])
                return decrypted.decode(self.engine.file_charset)
            return data.decode(self.engine.file_charset)
        except FileNotFoundError:
            raise TemplateDoesNotExist(origin)
'''


def write_loader(dest_path: str, key: bytes) -> None:
    """Write a Fernet-key-embedded loaders.py to *dest_path*."""
    os.makedirs(os.path.dirname(dest_path), exist_ok=True)
    code = LOADER_TEMPLATE.format(
        key_repr    = repr(key),
        marker_repr = repr(ENC_MARKER),
    )
    with open(dest_path, 'w', encoding='utf-8') as fh:
        fh.write(code)


# ======================================================================
#  Source-file helpers
# ======================================================================

def _read_source(path: str) -> str:
    """Read a Python source file, trying the most common encodings."""
    for enc in ('utf-8-sig', 'utf-8', 'cp1252', 'latin-1'):
        try:
            with open(path, encoding=enc) as fh:
                return fh.read()
        except (UnicodeDecodeError, LookupError):
            continue
    raise ValueError(f"Cannot decode {path!r} with any known encoding.")


def _node_text(node: ast.stmt, lines: list[str]) -> str:
    """Return the exact source text of *node* (including trailing newline)."""
    return ''.join(lines[node.lineno - 1 : node.end_lineno])


# ======================================================================
#  AST module analysis helpers
# ======================================================================

def _collect_defined_names(nodes: list[ast.stmt]) -> set[str]:
    """
    Return the set of names *assigned* or *imported* by *nodes*.

    Handles:
    - ``import x``, ``import x as y``            -> {x} / {y}
    - ``from m import x``, ``from m import x as y`` -> {x} / {y}
    - ``x = ...``, ``x: T = ...``, ``x += ...``  -> {x}
    - ``x, y = ...`` and nested tuples/lists     -> {x, y}
    - ``def foo``, ``class Foo``                 -> {foo} / {Foo}
    """
    names: set[str] = set()

    def _extract_targets(node: ast.expr) -> None:
        if isinstance(node, ast.Name):
            names.add(node.id)
        elif isinstance(node, (ast.Tuple, ast.List)):
            for elt in node.elts:
                _extract_targets(elt)
        # starred, subscript, attribute targets are not plain names

    for nd in nodes:
        if isinstance(nd, ast.Import):
            for alias in nd.names:
                names.add(alias.asname if alias.asname else alias.name.split('.')[0])
        elif isinstance(nd, ast.ImportFrom):
            for alias in nd.names:
                if alias.name == '*':
                    continue
                names.add(alias.asname if alias.asname else alias.name)
        elif isinstance(nd, ast.Assign):
            for target in nd.targets:
                _extract_targets(target)
        elif isinstance(nd, (ast.AnnAssign, ast.AugAssign)):
            _extract_targets(nd.target)
        elif isinstance(nd, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            names.add(nd.name)

    return names


def _has_unsafe_preamble(preamble_nodes: list[ast.stmt]) -> Optional[str]:
    """
    Return a human-readable reason if *preamble_nodes* contains constructs
    that cannot be safely referenced from another module; None if safe.

    The checks are conservative: a file is only flagged as unsafe if it
    clearly mutates global module state in ways that cannot be safely
    shared across a module boundary.
    """
    for nd in preamble_nodes:
        for child in ast.walk(nd):
            if isinstance(child, ast.Call):
                # exec(...) or eval(...)
                if isinstance(child.func, ast.Name) and child.func.id in ('exec', 'eval'):
                    return f"preamble calls {child.func.id}() at line {child.lineno}"
                # globals()[...] = ...  -- detected heuristically
                if (isinstance(child.func, ast.Attribute)
                        and isinstance(child.func.value, ast.Call)
                        and isinstance(child.func.value.func, ast.Name)
                        and child.func.value.func.id in ('globals', 'locals')
                        and child.func.attr in ('__setitem__', 'update')):
                    return f"preamble mutates globals()/locals() at line {child.lineno}"
    return None


def _names_referenced_in(node: ast.stmt) -> set[str]:
    """Return all Name ids that appear in the *load* context inside *node*."""
    return {
        n.id for n in ast.walk(node)
        if isinstance(n, ast.Name) and isinstance(n.ctx, ast.Load)
    }


def _analyze_module(
    tree: ast.Module,
    lines: list[str],
) -> tuple[list[ast.stmt], list[ast.stmt], list[ast.stmt], bool, str]:
    """
    Classify every top-level node in *tree* into one of three buckets.

    Returns
    -------
    import_nodes  : Import / ImportFrom statements  (safe to duplicate)
    preamble_nodes: all other non-def/class nodes that are safe to place
                    in part 1 before any definition (executed once only)
    def_nodes     : FunctionDef / AsyncFunctionDef / ClassDef nodes
                    (distributed across parts by size)
    is_safe       : False if the file cannot be split without changing semantics
    unsafe_reason : human-readable explanation when is_safe is False

    Splitting is unsafe when a non-import node that appears after a def/class
    **references a name defined by an earlier def/class**, because moving it to
    the preamble block (which precedes all definitions in part 1) would mean
    the reference resolves before the definition is executed.

    Pure-constant interleaved assignments (ones whose RHS only references
    builtins and import names, never a locally-defined function or class) are
    treated as late preamble and moved safely to part 1.

    Example of an *unsafe* interleaving::

        class Foo: ...
        REGISTRY = {'Foo': Foo}   # references local class Foo -> unsafe
        class Bar: ...

    Example of a *safe* interleaving::

        def helper(): ...
        MONTHS = {'jan': 1, 'feb': 2}   # no reference to helper -> safe
        def other(): ...
    """
    import_nodes:   list[ast.stmt] = []
    preamble_nodes: list[ast.stmt] = []
    def_nodes:      list[ast.stmt] = []

    # Accumulate locally-defined names as we walk in order
    locally_defined: set[str] = set()
    unsafe_at: Optional[int] = None
    unsafe_reason_str = ''

    for nd in tree.body:
        if isinstance(nd, (ast.Import, ast.ImportFrom)):
            import_nodes.append(nd)
            locally_defined |= _collect_defined_names([nd])
        elif isinstance(nd, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            locally_defined.add(nd.name)
            def_nodes.append(nd)
        else:
            # Non-import, non-def node.  Check whether it references any
            # locally-defined function/class name.
            referenced = _names_referenced_in(nd)
            local_refs = referenced & locally_defined
            # Filter out names that came purely from imports (safe to duplicate)
            import_defined = _collect_defined_names(import_nodes)
            dangerous_refs = local_refs - import_defined

            if dangerous_refs and def_nodes:  # after first def AND uses local name
                if unsafe_at is None:
                    unsafe_at = nd.lineno
                    unsafe_reason_str = (
                        f"module has a statement at line {nd.lineno} that "
                        f"references locally-defined name(s) "
                        f"{sorted(dangerous_refs)!r} after a function/class "
                        f"definition.  Moving it to the preamble would change "
                        f"execution order."
                    )
            preamble_nodes.append(nd)
            locally_defined |= _collect_defined_names([nd])

    if unsafe_at is not None:
        return import_nodes, preamble_nodes, def_nodes, False, unsafe_reason_str

    unsafe_preamble = _has_unsafe_preamble(preamble_nodes)
    if unsafe_preamble:
        return import_nodes, preamble_nodes, def_nodes, False, unsafe_preamble

    return import_nodes, preamble_nodes, def_nodes, True, ''


# ======================================================================
#  AST-based file splitter
# ======================================================================

def split_file(
    src_path: str,
    dest_dir: str,
    threshold: int = SPLIT_THRESHOLD,
) -> list[str]:
    """
    Split a large Python source file into several *_partN.py* files and
    write a thin re-export shim under the original filename.

    Algorithm
    ---------
    1.  Parse the module and classify nodes with ``_analyze_module``.
    2.  If the module is **not safe to split**, copy it as-is, emit a
        warning, and return ``[dest]`` so the caller can still attempt
        Pyarmor obfuscation on the single file.
    3.  Build **part 1**: import text + preamble text + first batch of
        definitions that fit within *threshold*.
    4.  Build **parts 2 +**: import text + a single cross-import line that
        pulls every preamble-defined name from part 1 + their definitions.
        The cross-import references already-evaluated objects; it does NOT
        re-execute the preamble.
    5.  Validate every generated part with ``ast.parse()``.  Abort the
        build (raise ``RuntimeError``) if any part has invalid syntax.
    6.  Propagate ``__all__`` to the shim so star-import filtering works.
    7.  Write the shim as the original filename in *dest_dir*.

    Returns
    -------
    List of written part-file paths (shim NOT included).
    If the file was not split (too small, or unsafe), returns a list
    containing only the single destination path.
    """
    source    = _read_source(src_path)
    raw_bytes = source.encode('utf-8')
    basename  = os.path.basename(src_path)
    stem      = os.path.splitext(basename)[0]

    # ── Trivially small: just copy ───────────────────────────────────────
    if len(raw_bytes) <= threshold:
        dest = os.path.join(dest_dir, basename)
        with open(dest, 'w', encoding='utf-8') as fh:
            fh.write(source)
        return [dest]

    # ── Parse ────────────────────────────────────────────────────────────
    lines: list[str] = source.splitlines(keepends=True)
    try:
        tree = ast.parse(source, filename=src_path)
    except SyntaxError as exc:
        _warn(f"{basename}: AST parse failed ({exc}) -- kept as single file.")
        dest = os.path.join(dest_dir, basename)
        with open(dest, 'w', encoding='utf-8') as fh:
            fh.write(source)
        return [dest]

    # ── Analyse ──────────────────────────────────────────────────────────
    import_nodes, preamble_nodes, def_nodes, is_safe, unsafe_reason = (
        _analyze_module(tree, lines)
    )

    if not is_safe:
        _warn(
            f"{basename}: cannot split safely -- {unsafe_reason}  "
            f"Keeping as single file ({len(raw_bytes)//1024} KB); "
            f"Pyarmor will attempt to obfuscate it directly."
        )
        dest = os.path.join(dest_dir, basename)
        with open(dest, 'w', encoding='utf-8') as fh:
            fh.write(source)
        return [dest]

    if not def_nodes:
        # Nothing to split (only imports / preamble)
        dest = os.path.join(dest_dir, basename)
        with open(dest, 'w', encoding='utf-8') as fh:
            fh.write(source)
        return [dest]

    # ── Build text segments ───────────────────────────────────────────────
    imports_text  = ''.join(_node_text(n, lines) for n in import_nodes)
    preamble_text = ''.join(_node_text(n, lines) for n in preamble_nodes)
    imports_bytes = len(imports_text.encode('utf-8'))
    preamble_bytes= len(preamble_text.encode('utf-8'))

    # Names that parts 2+ need to reference from part 1
    preamble_names = _collect_defined_names(preamble_nodes)
    # Also collect names from imports that appear in the preamble block
    # (they're already duplicated via imports_text, so don't cross-import)
    import_names   = _collect_defined_names(import_nodes)
    cross_names    = preamble_names - import_names  # only non-import preamble

    cross_import_text = ''
    if cross_names:
        names_str = ', '.join(sorted(cross_names))
        cross_import_text = f"from .{stem}_part1 import {names_str}\n"

    part1_prefix_bytes = imports_bytes + preamble_bytes
    partN_prefix_bytes = imports_bytes + len(cross_import_text.encode('utf-8'))

    # ── Greedy size-based grouping of def_nodes ───────────────────────────
    # Part 1 budget accounts for preamble; parts 2+ account for cross-import.
    chunks: list[list[ast.stmt]] = []
    current: list[ast.stmt] = []
    is_first_chunk = True
    current_prefix = part1_prefix_bytes
    current_size   = current_prefix

    for nd in def_nodes:
        ns = _node_text(nd, lines)
        nb = len(ns.encode('utf-8'))

        if nb + current_prefix > threshold:
            # This single definition is already larger than the budget.
            # Give it its own chunk and emit a warning — Pyarmor's actual
            # limit is higher than our conservative threshold.
            if current:
                chunks.append(current)
                current = []
            _warn(
                f"{basename}: definition at line {nd.lineno} "
                f"({nb // 1024} KB) exceeds threshold; "
                f"placed in its own chunk — Pyarmor may still accept it."
            )
            chunks.append([nd])
            is_first_chunk = False
            current_prefix = partN_prefix_bytes
            current_size   = current_prefix
            continue

        if current_size + nb > threshold:
            chunks.append(current)
            current        = [nd]
            is_first_chunk = False
            current_prefix = partN_prefix_bytes
            current_size   = current_prefix + nb
        else:
            current.append(nd)
            current_size += nb

    if current:
        chunks.append(current)

    if len(chunks) <= 1:
        # Splitting produced only one chunk — no point in splitting
        dest = os.path.join(dest_dir, basename)
        with open(dest, 'w', encoding='utf-8') as fh:
            fh.write(source)
        return [dest]

    # ── Generate and validate part files ─────────────────────────────────
    part_paths: list[str] = []

    for idx, chunk in enumerate(chunks, start=1):
        defs_text = ''.join(_node_text(n, lines) for n in chunk)

        if idx == 1:
            part_text = imports_text + '\n' + preamble_text + '\n' + defs_text
        else:
            part_text = imports_text + '\n' + cross_import_text + '\n' + defs_text

        # Validate before writing
        try:
            ast.parse(part_text, filename=f"<{stem}_part{idx}>")
        except SyntaxError as exc:
            raise RuntimeError(
                f"BUG: generated {stem}_part{idx} has invalid syntax: {exc}\n"
                f"Please report this with the original file."
            ) from exc

        part_name = f"{stem}_part{idx}.py"
        part_path = os.path.join(dest_dir, part_name)
        with open(part_path, 'w', encoding='utf-8') as fh:
            fh.write(part_text)
        part_paths.append(part_path)

    # ── Build the re-export shim ──────────────────────────────────────────
    shim_lines: list[str] = [
        "# Auto-generated re-export shim.  Do not edit.\n",
        "# Imports from each part in definition order.\n",
    ]

    # Propagate __all__ so star-import filtering is preserved
    for nd in preamble_nodes:
        if (isinstance(nd, ast.Assign)
                and any(
                    isinstance(t, ast.Name) and t.id == '__all__'
                    for t in nd.targets
                )):
            shim_lines.append(_node_text(nd, lines))
            break

    for idx in range(1, len(part_paths) + 1):
        shim_lines.append(f"from .{stem}_part{idx} import *\n")

    # Validate the shim syntax (it's simple but worth checking)
    shim_text = ''.join(shim_lines)
    try:
        ast.parse(shim_text, filename=f"<{stem} shim>")
    except SyntaxError as exc:
        raise RuntimeError(f"BUG: generated shim for {basename} has invalid syntax: {exc}") from exc

    shim_path = os.path.join(dest_dir, basename)
    with open(shim_path, 'w', encoding='utf-8') as fh:
        fh.writelines(shim_lines)

    return part_paths


# ======================================================================
#  File collection
# ======================================================================

def _collect_py_files(base_dir: str) -> list[str]:
    """Return all .py paths to obfuscate (respects OBFUSCATE_SKIP_DIRS)."""
    result: list[str] = []

    for script in PYTHON_SCRIPTS:
        p = os.path.join(base_dir, script)
        if os.path.isfile(p):
            result.append(p)

    for pkg in PYTHON_PACKAGES:
        pkg_dir = os.path.join(base_dir, pkg)
        if not os.path.isdir(pkg_dir):
            continue
        for root, dirs, files in os.walk(pkg_dir):
            dirs[:] = sorted(d for d in dirs if d not in OBFUSCATE_SKIP_DIRS)
            for f in sorted(files):
                if f.endswith('.py'):
                    result.append(os.path.join(root, f))

    return result


# ======================================================================
#  Pyarmor helpers
# ======================================================================

def _find_pyarmor(base_dir: str) -> str:
    """Locate the pyarmor executable; raise FileNotFoundError if absent."""
    py_dir = os.path.dirname(sys.executable)
    candidates = [
        os.path.join(py_dir, 'pyarmor'),
        os.path.join(py_dir, 'pyarmor.exe'),
        shutil.which('pyarmor') or '',
    ]

    curr = os.path.abspath(base_dir)
    while curr:
        candidates.extend([
            os.path.join(curr, 'venv', 'bin', 'pyarmor'),
            os.path.join(curr, 'venv', 'Scripts', 'pyarmor.exe'),
            os.path.join(curr, '.venv', 'bin', 'pyarmor'),
            os.path.join(curr, '.venv', 'Scripts', 'pyarmor.exe'),
        ])
        parent = os.path.dirname(curr)
        if parent == curr:
            break
        curr = parent

    for candidate in candidates:
        if candidate and os.path.isfile(candidate):
            return candidate

    raise FileNotFoundError(
        "pyarmor not found. Install it with:  pip install pyarmor"
    )


def _run_pyarmor_file(
    pyarmor_bin: str,
    src_file: str,
    out_dir: str,
    runtime_dir: Optional[str] = None,
) -> bool:
    """
    Obfuscate *src_file* and place the result in *out_dir*.

    If *runtime_dir* is supplied (path to a pre-generated
    ``pyarmor_runtime_000000`` directory), attempts
    ``pyarmor gen --use-runtime runtime_dir ...`` to avoid regenerating
    the runtime on every invocation.  Falls back to a plain
    ``pyarmor gen`` if ``--use-runtime`` is not supported by the installed
    version.

    The obfuscation runs inside a private temp directory; only the
    resulting ``.py`` file is copied to *out_dir*.  Any per-run runtime
    folder generated by Pyarmor is discarded.

    Returns True if a non-trivially-small output file was written.
    """
    fname = os.path.basename(src_file)

    def _attempt(cmd: list[str]) -> Optional[str]:
        """
        Run *cmd* inside a temp directory.
        If obfuscation succeeds, copies the resulting .py to a new named
        temp file that outlives the temp directory, and returns that path.
        Returns None on failure.
        """
        with tempfile.TemporaryDirectory() as tmp:
            r = subprocess.run(cmd + ['-O', tmp, src_file],
                               capture_output=True, text=True)
            if r.returncode != 0:
                return None
            for root, _, files in os.walk(tmp):
                if 'pyarmor_runtime_000000' in root:
                    continue
                if fname in files:
                    candidate = os.path.join(root, fname)
                    if os.path.getsize(candidate) >= MIN_OBFUSCATED_SIZE:
                        # Copy out before the TemporaryDirectory is deleted
                        fd, keeper = tempfile.mkstemp(suffix='.py')
                        os.close(fd)
                        shutil.copy2(candidate, keeper)
                        return keeper
        return None

    found: Optional[str] = None

    # Try with shared runtime first (avoids redundant per-file runtime gen)
    if runtime_dir and os.path.isdir(runtime_dir):
        found = _attempt([pyarmor_bin, 'gen', '--use-runtime', runtime_dir])

    # Fall back to standard invocation
    if found is None:
        found = _attempt([pyarmor_bin, 'gen'])

    if found:
        try:
            os.makedirs(out_dir, exist_ok=True)
            shutil.copy2(found, os.path.join(out_dir, fname))
            return True
        finally:
            # Clean up the temporary keeper file
            try:
                os.unlink(found)
            except OSError:
                pass
    return False


# ======================================================================
#  Step 1 -- Python obfuscation
# ======================================================================

def step_python(base_dir: str, dist_dir: str, fernet_key: bytes) -> bool:
    """
    Stage and obfuscate small Python files with Pyarmor.
    For files that exceed SPLIT_THRESHOLD (cannot be encrypted by Pyarmor trial),
    compile them directly to .pyc files instead of splitting.

    Returns True only if every file was processed without error.
    """
    import py_compile
    _banner("STEP 1 - Python obfuscation (Pyarmor / .pyc compilation)")

    pyarmor_bin = _find_pyarmor(base_dir)
    _info(f"pyarmor : {pyarmor_bin}")

    # ── Generate the shared runtime once ─────────────────────────────────
    _info("Generating Pyarmor runtime ...")
    r = subprocess.run(
        [pyarmor_bin, 'gen', 'runtime', '-O', dist_dir],
        capture_output=True, text=True, cwd=base_dir,
    )
    if r.returncode != 0:
        _warn("Runtime generation failed:\n" + (r.stderr or r.stdout or '').strip()[:300])
        runtime_dir = None
    else:
        _ok("pyarmor_runtime_000000/ written to dist/")
        # Locate the generated runtime so _run_pyarmor_file can reuse it
        runtime_dir = os.path.join(dist_dir, 'pyarmor_runtime_000000')
        if not os.path.isdir(runtime_dir):
            runtime_dir = None

    # ── Build staging directory for Pyarmor ───────────────────────────────
    stage_dir = os.path.join(base_dir, STAGE_DIR_NAME)
    if os.path.exists(stage_dir):
        shutil.rmtree(stage_dir)
    os.makedirs(stage_dir)

    all_sources = _collect_py_files(base_dir)
    pyc_compiled_count = 0
    fail_count = 0

    for src in all_sources:
        rel         = os.path.relpath(src, base_dir)
        basename    = os.path.basename(src)
        rel_dir     = os.path.dirname(rel)
        out_sub     = os.path.join(dist_dir, rel_dir)
        os.makedirs(out_sub, exist_ok=True)

        # Replace core/loaders.py with the Fernet-key-embedded version
        if rel.replace('\\', '/') == 'core/loaders.py':
            dest_subdir = os.path.join(stage_dir, rel_dir)
            os.makedirs(dest_subdir, exist_ok=True)
            write_loader(os.path.join(dest_subdir, basename), fernet_key)
            _info("Injected Fernet key into staged core/loaders.py")
            continue

        size = os.path.getsize(src)
        if size > SPLIT_THRESHOLD:
            # Cannot be encrypted with Pyarmor. Compile to .pyc instead.
            stem = os.path.splitext(basename)[0]
            dest_pyc = os.path.join(out_sub, f"{stem}.pyc")
            dest_py = os.path.join(out_sub, basename)
            try:
                py_compile.compile(src, cfile=dest_pyc, doraise=True)
                shim_code = (
                    "import os, runpy\n"
                    f"_g = runpy.run_path(os.path.join(os.path.dirname(__file__), '{stem}.pyc'), run_name=__name__)\n"
                    "globals().update(_g)\n"
                )
                with open(dest_py, "w", encoding="utf-8") as fh:
                    fh.write(shim_code)
                pyc_compiled_count += 1
                _info(f"[pyc]  {rel} ({size // 1024} KB) compiled directly to .pyc with loader shim")
            except Exception as exc:
                fail_count += 1
                _fail(f"Compilation failed for {rel}: {exc}")
        else:
            # Copy to stage dir for Pyarmor obfuscation
            dest_subdir = os.path.join(stage_dir, rel_dir)
            os.makedirs(dest_subdir, exist_ok=True)
            shutil.copy2(src, os.path.join(dest_subdir, basename))

    # ── Obfuscate every staged .py with Pyarmor ───────────────────────────
    staged: list[str] = []
    for root, dirs, files in os.walk(stage_dir):
        dirs[:] = [d for d in dirs if d != '__pycache__']
        for f in sorted(files):
            if f.endswith('.py'):
                staged.append(os.path.join(root, f))

    pyarmor_ok_count = 0

    for src_file in staged:
        rel     = os.path.relpath(src_file, stage_dir)
        rel_dir = os.path.dirname(rel)
        out_sub = os.path.join(dist_dir, rel_dir)

        success = _run_pyarmor_file(pyarmor_bin, src_file, out_sub, runtime_dir)

        if success:
            pyarmor_ok_count += 1
            _info(f"[obf]  {rel}")
        else:
            fail_count += 1
            _fail(f"Pyarmor failed: {rel}")
            # Echo the actual Pyarmor error for diagnostics
            r2 = subprocess.run(
                [pyarmor_bin, 'gen', '-O', out_sub, src_file],
                capture_output=True, text=True,
            )
            print("    " + (r2.stderr or r2.stdout or "").strip()[:300],
                  file=sys.stderr)

    # ── Copy migrations as plain .py (Django requires them at runtime) ────
    for pkg in PYTHON_PACKAGES:
        mig_src = os.path.join(base_dir, pkg, 'migrations')
        if os.path.isdir(mig_src):
            mig_dst = os.path.join(dist_dir, pkg, 'migrations')
            shutil.copytree(mig_src, mig_dst, dirs_exist_ok=True,
                            ignore=shutil.ignore_patterns('__pycache__'))
            _ok(f"Copied plain migrations: {pkg}/migrations/")

    # ── Clean up stage ────────────────────────────────────────────────────
    shutil.rmtree(stage_dir, ignore_errors=True)

    print()
    _ok(f"Python: {pyarmor_ok_count} obfuscated, {pyc_compiled_count} compiled to .pyc, {fail_count} failed.")
    return fail_count == 0


# ======================================================================
#  Step 2 -- JavaScript obfuscation
# ======================================================================

def step_javascript(base_dir: str, dist_dir: str) -> None:
    _banner("STEP 2 - JavaScript obfuscation (server.js)")

    src      = os.path.join(base_dir, 'whatsapp_service', 'server.js')
    dest_sub = os.path.join(dist_dir, 'whatsapp_service')
    dest     = os.path.join(dest_sub, 'server.js')
    os.makedirs(dest_sub, exist_ok=True)

    if not os.path.isfile(src):
        _warn("whatsapp_service/server.js not found -- skipping.")
        return

    npx = shutil.which('npx') or 'npx'
    cmd = [
        npx, '--yes', 'javascript-obfuscator', src,
        '--output', dest,
        '--compact', 'true',
        '--identifier-names-generator', 'hexadecimal',
        '--string-array', 'true',
        '--string-array-encoding', 'rc4',
        '--self-defending', 'true',
        '--disable-console-output', 'false',
    ]

    _info("Running javascript-obfuscator via npx ...")
    result = subprocess.run(cmd, capture_output=True, text=True, cwd=base_dir)

    if result.returncode == 0 and os.path.isfile(dest):
        _ok(f"server.js  {os.path.getsize(src) // 1024} KB -> {os.path.getsize(dest) // 1024} KB")
        return

    # Retry with a minimal flag set for compatibility with older npx versions
    cmd_min = [npx, '--yes', 'javascript-obfuscator', src,
               '--output', dest, '--compact', 'true', '--self-defending', 'true']
    _info("Retrying with minimal flags ...")
    r2 = subprocess.run(cmd_min, capture_output=True, text=True, cwd=base_dir)
    if r2.returncode == 0 and os.path.isfile(dest):
        _ok("server.js obfuscated (minimal flags)")
    else:
        shutil.copy2(src, dest)
        _warn("javascript-obfuscator failed -- copied original server.js")
        err = (r2.stderr or r2.stdout or "").strip()
        if err:
            _info("Error: " + err[:400])


# ======================================================================
#  Step 3 -- Template Fernet encryption
# ======================================================================

def step_templates(base_dir: str, dist_dir: str, fernet_key: bytes) -> None:
    _banner("STEP 3 - Template encryption (Fernet / AES-128-CBC + HMAC)")

    src_root  = os.path.join(base_dir, 'templates')
    dest_root = os.path.join(dist_dir, 'templates')

    if not os.path.isdir(src_root):
        _warn("templates/ not found -- skipping.")
        return

    count = 0
    for root, _, files in os.walk(src_root):
        for filename in files:
            src_path  = os.path.join(root, filename)
            rel       = os.path.relpath(src_path, src_root)
            dest_path = os.path.join(dest_root, rel)
            os.makedirs(os.path.dirname(dest_path), exist_ok=True)

            with open(src_path, 'rb') as fh:
                data = fh.read()

            if filename.endswith(('.html', '.txt', '.xml')):
                if not data.startswith(ENC_MARKER):
                    data = fernet_encrypt(data, fernet_key)
                with open(dest_path, 'wb') as fh:
                    fh.write(data)
                count += 1
            else:
                shutil.copy2(src_path, dest_path)

    _ok(f"{count} template file(s) encrypted with Fernet.")


# ======================================================================
#  Step 4 -- Static files & configs
# ======================================================================

def step_assets(base_dir: str, dist_dir: str) -> None:
    _banner("STEP 4 - Copying static files & configs")

    for folder in ('static', 'staticfiles'):
        src = os.path.join(base_dir, folder)
        if os.path.isdir(src):
            shutil.copytree(src, os.path.join(dist_dir, folder), dirs_exist_ok=True)
            _ok(f"Copied {folder}/")

    for fname in ('db.sqlite3', 'license.enc', 'requirements.txt', '.gitignore'):
        src = os.path.join(base_dir, fname)
        if os.path.isfile(src):
            shutil.copy2(src, os.path.join(dist_dir, fname))
            _ok(f"Copied {fname}")

    ws_src  = os.path.join(base_dir, 'whatsapp_service')
    ws_dest = os.path.join(dist_dir, 'whatsapp_service')
    os.makedirs(ws_dest, exist_ok=True)
    for fname in ('package.json', 'package-lock.json'):
        src = os.path.join(ws_src, fname)
        if os.path.isfile(src):
            shutil.copy2(src, os.path.join(ws_dest, fname))
            _ok(f"Copied whatsapp_service/{fname}")


# ======================================================================
#  Step 5 -- npm install
# ======================================================================

def step_npm(dist_dir: str) -> None:
    _banner("STEP 5 - npm install (dist/whatsapp_service)")
    ws_dir = os.path.join(dist_dir, 'whatsapp_service')
    npm    = shutil.which('npm.cmd') or shutil.which('npm') or 'npm'

    if not os.path.isfile(os.path.join(ws_dir, 'package.json')):
        _warn("No package.json found -- skipping npm install.")
        return

    r = subprocess.run(
        [npm, 'install', '--omit=dev'],
        cwd=ws_dir, capture_output=True, text=True,
    )
    if r.returncode == 0:
        _ok("npm dependencies installed.")
    else:
        _warn("npm install failed (run manually inside dist/whatsapp_service/).")
        print((r.stderr or r.stdout or '').strip()[:300], file=sys.stderr)


# ======================================================================
#  Entry point
# ======================================================================

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Build a Pyarmor-obfuscated dist/ copy of the project.",
    )
    parser.add_argument(
        '--clean',
        action='store_true',
        help="Delete existing dist/ (and dist_tmp/ if present) and exit.",
    )
    parser.add_argument(
        '--project-root',
        default=None,
        help="Project root directory. Default: parent of tools/ directory",
    )
    parser.add_argument(
        '--output-dir',
        default=None,
        help="Output directory for obfuscated code. Default: <project-root>/dist",
    )
    args = parser.parse_args()

    if args.project_root:
        base_dir = os.path.abspath(args.project_root)
    else:
        script_dir = os.path.dirname(os.path.abspath(__file__))
        base_dir = os.path.dirname(script_dir) if os.path.basename(script_dir) == 'tools' else script_dir

    if args.output_dir:
        dist_dir = os.path.abspath(args.output_dir)
        tmp_dir = dist_dir + "_tmp"
    else:
        dist_dir = os.path.join(base_dir, DIST_DIR_NAME)
        tmp_dir  = os.path.join(base_dir, DIST_TMP_NAME)

    if args.clean:
        for d in (dist_dir, tmp_dir):
            if os.path.exists(d):
                shutil.rmtree(d)
                print(f"Removed {d}")
        return 0

    print("=" * 66)
    print("  PROJECT OBFUSCATION BUILD TOOL")
    print(f"  Source  : {base_dir}")
    print(f"  Output  : {dist_dir}")
    print("=" * 66)

    # ── Atomic build: work inside tmp_dir; commit only on success ─────────
    if os.path.exists(tmp_dir):
        shutil.rmtree(tmp_dir)
    os.makedirs(tmp_dir)

    fernet_key = generate_fernet_key()
    _info("Generated fresh Fernet key for this build.")

    success = True
    try:
        py_ok = step_python(base_dir, tmp_dir, fernet_key)
        if not py_ok:
            _warn("Some Python files failed to obfuscate (see above).")
            success = False

        step_javascript(base_dir, tmp_dir)
        step_templates(base_dir, tmp_dir, fernet_key)
        step_assets(base_dir, tmp_dir)
        step_npm(tmp_dir)

    except Exception as exc:
        _fail(f"Unexpected build error: {exc}")
        shutil.rmtree(tmp_dir, ignore_errors=True)
        return 1

    # ── Commit: atomically replace dist/ ─────────────────────────────────
    # shutil.move handles cross-filesystem renames gracefully (falls back to
    # copytree + rmtree when os.rename would raise OSError).
    if not os.path.exists(tmp_dir):
        _fail("Build directory vanished before commit step -- aborting.")
        return 1
    if os.path.exists(dist_dir):
        shutil.rmtree(dist_dir)
    # Prefer os.rename (atomic on same filesystem); fall back to shutil.move
    # (copies across filesystems / drives when needed).
    try:
        os.rename(tmp_dir, dist_dir)
    except OSError:
        shutil.move(tmp_dir, dist_dir)

    print(f"\n{'=' * 66}")
    if success:
        print("  [DONE] Build complete!")
    else:
        print("  [DONE] Build complete (with warnings -- review output above).")
    print(f"  Output : {dist_dir}")
    print()
    print("  Deployment:")
    print("    1. Copy dist/ to the target machine.")
    print("    2. Create a venv and run:  pip install -r requirements.txt")
    print("    3. cd dist && python run_server.py")
    print('=' * 66)
    return 0 if success else 2


if __name__ == '__main__':
    sys.exit(main())
